ALTER TABLE "Organization"
  ADD COLUMN "uiDefaults" TEXT,
  ADD COLUMN "navDefault" TEXT,
  ADD COLUMN "dashDefault" TEXT;

ALTER TABLE "User"
  ALTER COLUMN "uiPalette" DROP NOT NULL,
  ALTER COLUMN "uiPalette" DROP DEFAULT,
  ALTER COLUMN "uiAccent" DROP NOT NULL,
  ALTER COLUMN "uiAccent" DROP DEFAULT,
  ALTER COLUMN "uiScale" DROP NOT NULL,
  ALTER COLUMN "uiScale" DROP DEFAULT,
  ALTER COLUMN "uiRadius" DROP NOT NULL,
  ALTER COLUMN "uiRadius" DROP DEFAULT,
  ALTER COLUMN "uiFont" DROP NOT NULL,
  ALTER COLUMN "uiFont" DROP DEFAULT;
