ALTER TABLE "BeatTake"
  ADD COLUMN "trimStartMs" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "trimEndMs" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "BeatVocalLayer"
  ADD COLUMN "reverb" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "eqLow" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "eqHigh" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "compress" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "doubler" BOOLEAN NOT NULL DEFAULT false;
